#!/usr/bin/env python3
"""
synap/runner.py — Lightweight AI Brain

This script:
1. Wakes up periodically (e.g. every 15 mins).
2. Reads cached market data (technicals, nansen) from MongoDB (generated by maintainer.py).
3. Evaluates the data using Claude.
4. Logs the decision and pushes any trade signals to the signals_queue for worker.py to execute.
"""

import os
import sys
import time
import json
import logging
from datetime import datetime, timezone

# Make sure project root is on path
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from backend.database import get_sync_db
from synap import claude_brain

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger(__name__)

# Poll every 60 minutes by default if no positions need urgent scanning
AI_SCAN_INTERVAL_SECONDS = 3600 

def run_brain():
    logger.info("=" * 70)
    logger.info("  🧠 AI BRAIN DECISION ENGINE")
    logger.info(f"  Claude model:  {os.getenv('CLAUDE_MODEL', 'claude-sonnet-4-5')}")
    logger.info("=" * 70)

    db = get_sync_db()

    while True:
        try:
            logger.info("\n🔍 Starting new AI evaluation cycle...")
            
            # 1. Load the latest market intelligence from MongoDB
            market_data_doc = db.market_data.find_one({"key": "market_intelligence"})
            if not market_data_doc or "value_json" not in market_data_doc:
                logger.warning("No market intelligence found in DB. Waiting for maintainer.py...")
                time.sleep(60)
                continue
                
            intel = json.loads(market_data_doc["value_json"])
            
            # Reconstruct the components expected by claude_brain
            technicals = intel.get("technicals", {})
            sentiment_data = intel.get("sentiment", {})
            funding_rates = intel.get("funding_rates", {})
            watchlist = intel.get("watchlist", [])
            
            # Read Nansen data directly from nansen_cache collection
            nansen_data = {"perp_screener": None, "smart_money_flows": {}, "token_trends": None}
            
            today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            
            # Fetch Perp Screener
            perp_doc = db.nansen_cache.find_one({"cache_key": f"perp_screener_{today_str}"})
            if perp_doc:
                nansen_data["perp_screener"] = json.loads(perp_doc["response_json"])
                
            # Fetch Smart Money Netflow
            sm_doc = db.nansen_cache.find_one({"cache_key": "sm_netflow_all_24h"})
            if sm_doc:
                nansen_data["smart_money_flows"] = json.loads(sm_doc["response_json"])
                
            # Fetch Token Screener (Token Trends)
            token_doc = db.nansen_cache.find_one({"cache_key": "token_screener_24h"})
            if token_doc:
                nansen_data["token_trends"] = json.loads(token_doc["response_json"])

            if not watchlist:
                # Fallback: try the active_watchlist doc saved separately by maintainer
                wl_doc = db.market_data.find_one({"key": "active_watchlist"})
                if wl_doc and "value_json" in wl_doc:
                    watchlist = json.loads(wl_doc["value_json"])
                    logger.info(f"📋 Loaded watchlist from active_watchlist fallback: {len(watchlist)} coins")

            if not watchlist:
                logger.warning("⏳ Watchlist is empty — maintainer.py hasn't completed its first cycle yet. Waiting 60s...")
                time.sleep(60)
                continue

            logger.info(f"👀 Evaluating {len(watchlist)} coins: {', '.join(watchlist)}")
            
            # 2. Mock a portfolio for Claude's sizing logic
            # In a multi-user environment, Claude makes a "Master Decision" assuming 
            # a standard account. The worker.py scales it for each user later.
            mock_portfolio = {
                "total_equity": 1000.0,
                "cash": 1000.0,
                "open_position_count": 0,
                "win_rate": 50.0
            }
            
            # 3. Call Claude API
            logger.info("🧠 Consulting Claude AI...")
            decision = claude_brain.get_ai_decision(
                technicals,
                sentiment_data,
                nansen_data,
                mock_portfolio,
                funding_rates,
                watchlist
            )
            
            if not decision:
                logger.warning("Claude returned no decision.")
                time.sleep(AI_SCAN_INTERVAL_SECONDS)
                continue

            # Validate decision
            validated = claude_brain.validate_decision(decision)
            
            if validated.get("market_assessment"):
                logger.info(f"📝 Market view: {validated['market_assessment']}")
            if validated.get("skip_reason"):
                logger.info(f"⏸️ Skip reason: {validated['skip_reason']}")
                
            # 4. Push Trades to Signal Queue
            trades = validated.get("trades", [])
            if trades:
                logger.info(f"🚀 Claude generated {len(trades)} trade signals!")
                for trade in trades:
                    coin = trade["coin"]
                    action = trade["action"]
                    
                    signal_doc = {
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                        "strategy_id": "ALGO AI BOT",
                        "coin": coin,
                        "action": action,
                        "side": action.replace("OPEN_", ""),
                        "entry_price": trade.get("entry_price"),
                        "stop_loss": trade.get("stop_loss"),
                        "take_profit_1": trade.get("take_profit_1"),
                        "leverage": trade.get("leverage", 10),
                        "reasoning": trade.get("reasoning", ""),
                        "conviction": trade.get("conviction", 0.5),
                        "status": "PENDING"
                    }
                    
                    db.signals_queue.insert_one(signal_doc)
                    logger.info(f"📥 Pushed {action} on {coin} to signals_queue.")
            
            # 5. Log decision for dashboard history
            # The dashboard expects 'user_id' for segregation. Master signals don't have a specific user.
            # However, for the AI Signals feed on the frontend to work, we log the master decision.
            db.decision_logs.insert_one({
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "decision_json": json.dumps(validated)
            })
            
            logger.info("✅ Cycle complete. Sleeping...")
            
        except Exception as e:
            logger.error(f"❌ Runner loop error: {e}", exc_info=True)
            
        # Sleep until next scan
        time.sleep(AI_SCAN_INTERVAL_SECONDS)

if __name__ == "__main__":
    run_brain()
